image: maven:latest

stages:
  - build
  - test
  - integration
  - report

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

cache:
  paths:
    - target/

project_compile:
  stage: build
  script:
    - source /home/gitlab-runner/.profile
    - ./install-dependencies.sh
    - mvn $MAVEN_CLI_OPTS -U clean compile

junit_tests:
  stage: test
  script:
    - source /home/gitlab-runner/.profile
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
    paths:
        - target/surefire-reports/TEST-*.xml
    expire_in: 1 week

mpjnative_it_tests:
  stage: integration
  script:
    - source /home/gitlab-runner/.profile
    - mvn $MAVEN_CLI_OPTS -Popenmpi verify -Dhostfile=${HOSTFILE}
    - cat target/site/jacoco/index.html | grep -o Total[^%]*% | sed "s/<.*>//" | sed "s/Total/Total Coverage /"
  artifacts:
    when: always
    reports:
      junit:
        - target/failsafe-reports/TEST-*.xml
    paths:
      - target/failsafe-reports/TEST-*.xml
      - target/site/*
    expire_in: 1 week

.mpijava_it_tests:
  stage: integration
  allow_failure: true
  script:
    - source /home/gitlab-runner/.profile
    - mvn $MAVEN_CLI_OPTS -Pmpijava verify -Dhostfile=${HOSTFILE}
    - cat target/site/jacoco/index.html | grep -o Total[^%]*% | sed "s/<.*>//" | sed "s/Total/Total Coverage /"
  artifacts:
    when: always
    reports:
      junit:
        - target/failsafe-reports/TEST-*.xml
    paths:
      - target/failsafe-reports/TEST-*.xml
      - target/site/*
    expire_in: 1 week

javadoc:
  stage: report
  script:
    - source /home/gitlab-runner/.profile
    - mvn $MAVEN_CLI_OPTS site
  only:
    - develop

publish:
  stage: report
  script:
    - source /home/gitlab-runner/.profile
    - mvn $MAVEN_CLI_OPTS site
    - cd core/target
    - git clone --single-branch --branch gh-pages https://github.com/handist/collections.git
    - rm -rf collections/master-latest
    - mkdir collections/master-latest
    - cp -r site/* collections/master-latest/
    - cd collections
    - git add master-latest
    - git commit -m "${CI_COMMIT_MESSAGE}"
    - git remote set-url origin https://${GITHUB_USER}:${GITHUB_OAUTH}@github.com/handist/collections.git
    - git push origin gh-pages
  only:
    - master
