image: maven:latest

stages:
  - build
  - test
  - integration
  - report

variables:
  MAVEN_CLI_OPTS: "--batch-mode -Pmpijava"

cache:
  paths:
    - target/

project_compile:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

junit_tests:
  stage: test
  script:
    - source /home/gitlab-runner/.profile
    - mvn $MAVEN_CLI_OPTS test
    - cat target/site/jacoco/index.html | grep -o Total[^%]*% | sed "s/<.*>//" | sed "s/Total/Total Coverage /"
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
    paths:
        - target/surefire-reports/TEST-*.xml
    expire_in: 1 week

integration_tests:
  stage: integration
  script:
    - source /home/gitlab-runner/.profile
    - mvn $MAVEN_CLI_OPTS verify
    - cat target/site/jacoco/index.html | grep -o Total[^%]*% | sed "s/<.*>//" | sed "s/Total/Total Coverage /"
  artifacts:
    when: always
    reports:
      junit:
        - target/failsafe-reports/TEST-*.xml
    paths:
      - target/failsafe-reports/TEST-*.xml
      - target/site/*
    expire_in: 1 week

javadoc:
  stage: report
  script:
    - source /home/gitlab-runner/.profile
    - mvn $MAVEN_CLI_OPTS site
  only:
    - develop

publish:
  stage: report
  script:
    - source /home/gitlab-runner/.profile
    - mvn $MAVEN_CLI_OPTS site
    - cd target
    - git clone --single-branch --branch gh-pages https://github.com/handist/handistCollections.git
    - rm -rf handistCollections/master-latest
    - mkdir handistCollections/master-latest
    - cp -r site/* handistCollections/master-latest/
    - cd handistCollections
    - git add master-latest
    - git commit -m "${CI_COMMIT_MESSAGE}"
    - git remote set-url origin https://${GITHUB_USER}:${GITHUB_OAUTH}@github.com/handist/handistCollections.git
    - git push origin gh-pages
  only:
    - master
