image: maven:latest

stages:
  - build
  - test
  - integration

variables:
  MAVEN_CLI_OPTS: "--batch-mode -Pmpijava"

cache:
  paths:
    - target/

project_compile:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

junit_tests:
  stage: test
  script:
    - source /home/gitlab-runner/.profile
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
    paths:
        - target/surefire-reports/TEST-*.xml
    expire_in: 1 week

integration_tests:
  stage: integration
  script:
    - source /home/gitlab-runner/.profile
    - mvn $MAVEN_CLI_OPTS verify
    - cat target/site/jacoco/index.html | grep -o Total[^%]*% | sed "s/<.*>//" | sed "s/Total/Total Coverage /"
  artifacts:
    when: always
    reports:
      junit:
        - target/failsafe-reports/TEST-*.xml
    paths:
      - target/failsafe-reports/TEST-*.xml
      - target/site/*
    expire_in: 1 week